name: UI Tests - Android

on: [pull_request]

jobs:
  run-visual-regression-android:
    runs-on: macos-11
    if: ${{ true }}

    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: SKDs - download required images
        run: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;default;x86_64"

      - name: SDKs - accept licenses
        run: y | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Emulator - Create
        run: $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_31 --device 'Nexus 5X' --package "system-images;android-31;default;x86_64" --sdcard 512M

      - name: Emulator - Boot
        run: $ANDROID_HOME/emulator/emulator -memory 4096 -avd Pixel_API_31 -wipe-data -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &

      - name: ADB Wait For Device
        run: adb wait-for-any-device
        timeout-minutes: 3

      - name: Run Owl Build
        run: yarn owl:build:android

      - name: Run Owl Test
        run: yarn owl:test:android

      - name: Store screenshots as artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        if: failure()
        with:
          name: owl-screenshots
          path: .owl
